name: aai_job

on:
    push:
        branches:
            - main

env:
    ENV: dev
    REGION: us-west-1

jobs:
    Deploy:
        name: Deploy AAI AWS infrastructure
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # terraform setup
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
              run: |
                echo ""
                echo "------------------------"
                echo "Terraform version"
                echo "------------------------"
                terraform --version

            # python 3.9 setup / the latest python supported by AWS
            - name: Setup python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: "3.9"
              run: |
                echo ""
                echo "------------------------"
                echo "Python version"
                echo "------------------------"
                python --version

            # setup other required tools
            - name: Setup Other tools
              run: |
                echo ""
                echo "------------------------"
                echo "Check parallel"
                echo "------------------------"
                [ "$(command -v parallel)" == "" ] && sudo npm -g install parallel || which parallel
                parallel --version
                echo ""
                echo "------------------------"
                echo "Check serverless"
                echo "------------------------"
                [ "$(command -v serverless)" == "" ] && sudo npm -g install serverless || which serverless
                serverless --version
                echo ""
                echo "------------------------"
                echo "Check awscli"
                echo "------------------------"
                [ "$(command -v aws)" == "" ] && sudo npm -g install awscli || which aws
                aws --version

            # deploys Terraform first, unit tests lambdas and deploys them
            # - name: Deploy
            #   run: ./deploy.sh
            #   shell: bash
            #   env:
            #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     AWS_DEFAULT_REGION: $(REGION)
            #     TF_VAR_env: $(ENV)
            #     TF_INPUT: false
            #     TF_IN_AUTOMATION: true

            # run integration tests
            # - name: Integration tests
            #   run: ./runIntegrationTests.sh
            #   shell: bash
            #   env:
            #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     AWS_DEFAULT_REGION: $(REGION)
